### ISSUE TITLE
ESL Ex. 5.15 part (a) solution

### ISSUE THREAD

**Issue by shubosun0113** [YuhangZhou88/ESL_Solution#12]
Hi Yuhang, I thought I should have seen a typo in your Ex. 5.15 (a)'s answer, but I'm not sure if I'm correct.

Below the sentence "Therefore, by definition of $K$ we have", the first line contains a constant $\gamma_i$ that has not been defined. Should this $\gamma_i$ be $\lambda_i$ instead, as what you defined in the denominator of the inner product $H_K$? Thank you!

**Comment by YuhangZhou88** [comment]
thanks! 

gamma_i is from equation (5.45) in the text, but there's indeed a type in the second equation where lambda_i in the numerator should be gamma_i

**Comment by shubosun0113** [comment]
Thank u for your explanation! I'm a first-year phd in stats who is self-learning the ESL and your solution really helps a lot!
