### ISSUE TITLE
Exercise 10.3

### ISSUE THREAD

**Issue by Jasonli1997** [YuhangZhou88/ESL_Solution#6]
I'm kinda confused by the conditional expectation in this exercise and what the expectation is taken with respect to. Moreover, could you explain how you went from $E[h1(Xs)+h2(Xc)|Xs]$ to E[h1(Xs)|Xc]+Xc?

**Comment by YuhangZhou88** [comment]
Thanks, that is a typo, I've fixed it.

**Comment by Jasonli1997** [comment]
Thanks for the fix but why is the conditional expectation taken w.r.t. Xc instead of Xs in your solution when 10.49 is E[h1(Xs)+h2(Xc)|Xs]?

**Comment by YuhangZhou88** [comment]
Thanks, that was indeed a mistake, I've fixed it.
